name: Deploy Lambda Function

on:
  push:
    branches: [ main ]
    paths: [ 'lambda/**' ]
  workflow_run:
    workflows: ["Run Tests"]
    types: [completed]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy Lambda function
      run: |
        cd lambda
        zip ../lambda-deployment.zip index.js
        cd ..
        aws lambda update-function-code \
          --function-name web-portal-presign \
          --zip-file fileb://lambda-deployment.zip
        
        echo "Lambda function updated successfully"