name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Clean install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install
    
    - name: Run linting
      run: npm run lint
    
    - name: Run type checking
      run: npm run type-check
    
    - name: Run frontend tests
      run: npm test
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: success()

  test-lambda:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: lambda/package.json
    
    - name: Install Lambda dependencies
      run: |
        cd lambda
        npm install
    
    - name: Run Lambda tests
      run: |
        cd lambda
        npm test
    
    - name: Upload Lambda coverage
      uses: codecov/codecov-action@v3
      if: success()
      with:
        directory: lambda